steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/enterprise-rag-repo/evals:latest'
      - '-f'
      - 'docker/evals.Dockerfile'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/enterprise-rag-repo/evals:latest'

timeout: '1800s'
